name: rust-bf
version: 4.0.0
summary: A super fast 8bit brainfuck interpreter written in rust
description: |
  rust-bf is a command line program for running 8bit brainfuck
  programs at a speed that means you can overflow 8bit easily.

  Use rust-bf --help to find out how to use the program.

base: core20
confinement: strict

parts:
  rust-bf:
    build-packages: [gcc-multilib]
    plugin: rust
    source: .

apps:
  rust-bf:
    command: bin/rust-bf
    plugs: 
        - home
